# Generated by Django 3.0.2 on 2020-07-05 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0089_auto_20200702_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistration',
            name='dOB',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
