# Generated by Django 3.0.2 on 2020-07-06 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0091_auto_20200706_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistration',
            name='dOB',
            field=models.CharField(blank=True, default='No birth date to show', max_length=100),
        ),
    ]
