# Generated by Django 3.0.2 on 2020-07-13 03:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0092_auto_20200706_0129'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('ContactId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=100)),
                ('email', models.EmailField(blank=True, default='', max_length=50)),
                ('comment', models.CharField(default='', max_length=1000)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
